/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minifyjpeg.h"

output *
minify_proc_1_svc(input arg1,  struct svc_req *rqstp)
{
	static output  result;

	/*
	 * insert server code here
	 */

	return &result;
}
